apiVersion: apps/v1
kind: Deployment
metadata:
  name: depi-app
  namespace: depi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depi-app
  template:
    metadata:
      labels:
        app: depi-app
    spec:
      containers:
        - name: depi-app
          image: 532334935385.dkr.ecr.us-east-1.amazonaws.com/depi:12
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 5000
